baseURL: https://websitevaleriaopre.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get to know me!
    subtitle: 
       Valeria Opre, LBS Graduate
    title: It is what it is.
      Until it's not.
  blog: {}
  contact:
    address:
      - city: London, UK 
        country: Country
        street: Euston Road 365
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: vopre.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7776 954445
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/valeria.opre/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/valeriaopre/?hl=it
      - icon: fa-github
        label: GitHub
        url: https://github.com/valeriaopre
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/valeriaopre/
  image: 'bello.jpg'
  name: Valeria Opre
  navigation:
    button1:
    #  - name: My projects
     #   url: blogs
    links:
      - name: Home
        url: '#'
      - name: My project portfolio 
        url: blogs
      - name: Where my life beginns
        url: life
      - name: Social Projects
        url: elements/SocialProjects
      - name: Equity Research Pitches
        url: equity
    menu: Menu
    subtitle: Personal Portfolio
    title: Valeria Opre
  tiles:
    enable: yes
    showcase:
      - image: Fototessera.jpg
        subtitle: Biography
        title: About me
        url: post/post1
      - image: trump.jpg
        subtitle: Increasing political polarisation in the US could lead to worrying health issues
        title: US elections and vaccinations rate
        url: blogs/blog11
      - image: community.jpg
        subtitle: Being part of a community has always been a key pillar to my life.
        title: Social Projects
        url: elements/socialProjects
      - image: word.jpg
        subtitle: New medical standards and increased GDP might lead the way to higher Life Expectancy for all countries.
        title: Life Expectancy comparison between my home countries; An overview
        url: blogs/blog3
        image: santander.jpg
        subtitle: Restrictive measures highly influenced the number of rentals
        title: Change in the of rentals bike in 2020 because of national lockdowns
        url: blogs/blog2
      - image: cover.jpg
        subtitle: A sweedish construction company that even Greta would approve of!
        title: Winning equity research pitch awarded from McKinsey, June 2021
        url: equity/Skanska.pdf
      - image: salmon.jpg
        subtitle: How much is the Fish?
        title: Winning equity research pitch awarded from McKinsey, January 2021
        url: equity/Mowi.pdf

  #two:
  #  buttonText: Projects
#    enable: yes
 #   subtitle: "I would like to take you on a journey and show you what drives me into waking up everyday and pushing through.
  #  To know the person one must understand the reasons lying behind her actions."
  #  title: Curiosity meets workaholic: a love story
   # url: blogs
