baseURL: https://websitevaleriaopre.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get to know me!
    subtitle: 
       Valeria Opre, LBS Graduate
    title: It is what it is.
      Until it's not.
  blog: {}
  contact:
    address:
      - city: London, UK 
        country: Country
        street: Euston Road 365
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: vopre.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7776 954445
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/valeria.opre/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/valeriaopre/?hl=it
      - icon: fa-github
        label: GitHub
        url: https://github.com/valeriaopre
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/valeriaopre/
  image: 'bello.jpg'
  name: Valeria Opre
  navigation:
   # button1:
    #  - name: My projects
     #   url: blogs
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Social Projects
        url: elements
    menu: Menu
    subtitle: Personal Portfolio
    title: Valeria Opre
  tiles:
    enable: yes
    showcase:
      - image: Fototessera.jpg
        subtitle: Biography
        title: About me
        url: post/post1
      - image: pic02.jpg
        subtitle: something
        title: US elections and vaccinations rate
        url: blogs/blog1
      - image: pic03.jpg
        subtitle: Description two
        title: Project two
        url: blogs/blog2
      - image: pic04.jpg
        subtitle: Description three
        title: Project three
        url: blogs/blog3
      - image: pic05.jpg
        subtitle: Description four
        title: Project four
        url: blogs/blog4

  #two:
  #  buttonText: Projects
#    enable: yes
 #   subtitle: "I would like to take you on a journey and show you what drives me into waking up everyday and pushing through.
  #  To know the person one must understand the reasons lying behind her actions."
  #  title: Curiosity meets workaholic: a love story
   # url: blogs
